//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_company_programm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Сonstruction
    {
        public Application_Сonstruction()
        {
            this.Client = new HashSet<Client>();
            this.Type_Reactor = new HashSet<Type_Reactor>();
            this.Сontractors = new HashSet<Сontractors>();
        }
    
        public int Ac_Id { get; set; }
        public System.DateTime Ac_Start_date { get; set; }
        public System.DateTime Ac_End_date { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Type_Reactor> Type_Reactor { get; set; }
        public virtual ICollection<Сontractors> Сontractors { get; set; }
    }
}
