//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_company_programm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Application_Сonstruction = new HashSet<Application_Сonstruction>();
        }
    
        public int C_Id { get; set; }
        public string C_Name { get; set; }
        public string C_Mail { get; set; }
        public int C_Number_phone { get; set; }
        public string C_Address { get; set; }
        public string C_Image { get; set; }
    
        public virtual ICollection<Application_Сonstruction> Application_Сonstruction { get; set; }
    }
}
