//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_company_programm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application_Сonstruction> Application_Сonstruction { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Type_Reactor> Type_Reactor { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Сontractors> Сontractors { get; set; }
    }
}
