//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_company_programm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Reactor
    {
        public Type_Reactor()
        {
            this.Application_Сonstruction = new HashSet<Application_Сonstruction>();
        }
    
        public int Tr_Id { get; set; }
        public string Tr_Name { get; set; }
        public Nullable<decimal> Tr_Cost { get; set; }
    
        public virtual ICollection<Application_Сonstruction> Application_Сonstruction { get; set; }
    }
}
